--!nocheck

local MapDataBook = {}

MapDataBook.DifficultyColors = {
    ["1"] = Color3.fromRGB(255, 255, 255),
    ["2"] = Color3.fromRGB(255, 255, 255),
    ["3"] = Color3.fromRGB(255, 255, 255),
    ["4"] = Color3.fromRGB(255, 255, 255),
    ["5"] = Color3.fromRGB(255, 255, 255),
    ["6"] = Color3.fromRGB(255, 255, 255),
    ["7"] = Color3.fromRGB(255, 255, 255),

    ["Unrated"] = Color3.fromRGB(255, 255, 255)
}

return MapDataBook
